name: Deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - vercel
  pull_request:
    branches:
      - vercel
    types:
      - opened
      - synchronize

jobs:
  deploy:
    name: Deploy
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-deps-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Pull production environment
        if: ${{ startsWith(github.ref, 'refs/heads/vercel') }}
        run: |
          vercel pull \
            --yes \
            --environment=production \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to production
        if: ${{ startsWith(github.ref, 'refs/heads/vercel') }}
        run: |
          pnpm build
          vercel deploy \
            --prod \
            --prebuilt \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull production environment
        if: ${{ github.event.pull_request.state == 'open' }}
        run: |
          vercel pull \
            --yes \
            --environment=preview \
            --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy preview environment
        if: ${{ github.event.pull_request.state == 'open' }}
        run: |
          pnpm build
          vercel deploy \
            --prebuilt \
            --token=${{ secrets.VERCEL_TOKEN }} \
            > deployment-url.txt
          echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> "$GITHUB_OUTPUT"
          cat deployment-url.txt

      - name: Update comment on PR
        if: ${{ github.event.pull_request.state == 'open' }}
        env:
          DEPLOYMENT_URL: ${{ steps.preview.outputs.DEPLOYMENT_URL }}
        uses: actions/github-script@v6
        with:
          script: |
            // Find previous comment
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const comment = comments.find(({ body }) => body.startsWith('Deployment preview ready!'));

            // Remove comment
            comment && await github.rest.issues.deleteComment({
              comment_id: comment.id,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Add comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Deployment preview ready!\n\n[${{ env.DEPLOYMENT_URL }}](${{ env.DEPLOYMENT_URL }})"
            });
